- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
    username: "probird5"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install

# Included task files
- import_tasks: tasks/initial_setup.yml
- import_tasks: tasks/golang.yml
- import_tasks: tasks/1password.yml
  #- import_tasks: tasks/docker.yml
