- hosts: localhost
  vars:
    personal: "{{ lookup('env', 'HOME') }}/personal"
    username: "probird5"
  pre_tasks:
  - name: Update DNF
    become: true
    dnf:
      update_cache: true
      state: present
    tags:
      - install

  tasks:
    - import_tasks: tasks/initial_setup.yml
    - import_tasks: tasks/golang.yml
    - import_tasks: tasks/1password.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/nvim.yml

