- name: "Update Package Lists"
  ansible.builtin.dnf:
    update_cache: yes
  become: true

- name: Install gnupg for adding keys
  ansible.builtin.dnf:
    name: gnupg
    state: present
  become: true

- name: "1Password | Add Repository"
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/rpm/stable/x86_64/1password.repo
    dest: /etc/yum.repos.d/1password.repo
  become: true

- name: "1Password | Import GPG Key"
  ansible.builtin.rpm_key:
    state: present
    key: https://downloads.1password.com/linux/keys/1password.asc
  become: true

- name: "Install 1Password"
  ansible.builtin.dnf:
    name: 1password
    state: present
    update_cache: yes
  become: true

