- name: "Docker | Update APT cache"
  ansible.builtin.apt:
    update_cache: yes

- name: "Docker | Install dependencies"
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: "Docker | Add Docker’s official GPG key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: "Docker | Add Docker’s stable repository"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    mode: "0644"

- name: "Docker | Install Docker Engine"
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: "Docker | Enable and start Docker service"
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: "Docker | Add user to the 'docker' group"
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    append: yes
    groups: docker

