# tmux_playbook.yml
- block:
    - name: "Install tmux"
      ansible.builtin.apt:
        name: tmux
        state: present
      become: true
      tags: tmux_install

    - name: "Download .tmux.conf from GitHub"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/probird5/dotfiles/main/.tmux.conf"
        dest: "~/.tmux.conf"
        mode: '0644'
      tags: tmux_config

    - name: "Clone TPM (Tmux Plugin Manager)"
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"
        version: "master"
      tags: tmux_tpm

  tags: 
    - tmux

