- name: Bootstrap development environment
  hosts: localhost
  become: yes
  become_user: root

  vars:
    target_user: "{{ username }}"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages with apt
      ansible.builtin.apt:
        name:
          - git
          - tmux
          - zsh
          - alacritty
          - i3
          - kitty
          - neofetch
          - picom
          - polybar
          - rofi
          - tree
          - unzip
          - xorg
          - xclip
        state: present

    # Clone dotfiles repository
    - name: Clone dotfiles repository
      ansible.builtin.git:
        repo: 'https://github.com/probird5/dotfiles'
        dest: /home/{{ username }}/dotfiles

    # Alacritty
    - name: Ensure alacritty config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/alacritty
        state: directory

    - name: Copy alacritty configuration
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/alacritty/alacritty.yml
        dest: /home/{{ username }}/.config/alacritty/alacritty.yml

    # i3
    - name: Ensure i3 config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/i3
        state: directory

    - name: Copy i3 configuration
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/i3/config
        dest: /home/{{ username }}/.config/i3/config

    # kitty
    - name: Ensure kitty config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/kitty
        state: directory

    - name: Copy kitty configuration
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/kitty/kitty.conf
        dest: /home/{{ username }}/.config/kitty/kitty.conf

    # Neofetch
    - name: Ensure neofetch config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/neofetch
        state: directory

    - name: Copy neofetch configuration
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/neofetch/config.conf
        dest: /home/{{ username }}/.config/neofetch/config.conf

    # Neovim
    - name: Ensure nvim config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/nvim
        state: directory

    - name: Copy nvim init file
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/nvim/init.lua
        dest: /home/{{ username }}/.config/nvim/init.lua

    - name: Ensure nvim lua directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/nvim/lua
        state: directory

    - name: Copy nvim lua directory
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/nvim/lua/
        dest: /home/{{ username }}/.config/nvim/lua/
        directory_mode: yes

    # Picom
    - name: Ensure picom config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/picom
        state: directory

    - name: Copy picom configuration
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/picom/picom.conf
        dest: /home/{{ username }}/.config/picom/picom.conf

    # Polybar
    - name: Ensure polybar config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/polybar
        state: directory

    - name: Copy polybar configuration directory
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/polybar/
        dest: /home/{{ username }}/.config/polybar/
        directory_mode: yes

    # Rofi
    - name: Ensure rofi config directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.config/rofi
        state: directory

    - name: Copy rofi configuration
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/rofi/config.rasi
        dest: /home/{{ username }}/.config/rofi/config.rasi

    - name: Copy rofi powermenu
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/rofi/powermenu.rasi
        dest: /home/{{ username }}/.config/rofi/powermenu.rasi

    # Backgrounds
    - name: Ensure backgrounds directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/Pictures/backgrounds
        state: directory

    - name: Copy backgrounds
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/background/
        dest: /home/{{ username }}/Pictures/backgrounds/
        directory_mode: yes

    # Ensure the font directory exists
    - name: Ensure font directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.local/share/fonts
        state: directory

    # Download Iosevka Font Zip
    - name: Download Iosevka Font Zip
      ansible.builtin.get_url:
        url: 'https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Iosevka.zip'
        dest: /tmp/Iosevka.zip
        mode: '0440'

    - name: Ensure /tmp/Iosevka directory exists
      ansible.builtin.file:
        path: /tmp/Iosevka
        state: directory
        recurse: yes

    # Unzip Iosevka Font
    - name: Unzip Iosevka Font
      ansible.builtin.unarchive:
        src: /tmp/Iosevka.zip
        dest: /tmp/Iosevka/
        remote_src: yes

    # Move Iosevka Fonts to Fonts Directory
    - name: Move Iosevka Fonts to Fonts Directory
      ansible.builtin.copy:
        src: /tmp/Iosevka/
        dest: /home/{{ username }}/.local/share/fonts
        remote_src: yes

    # Download JetBrainsMono Font Zip
    - name: Download JetBrainsMono Font Zip
      ansible.builtin.get_url:
        url: 'https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip'
        dest: /tmp/JetBrainsMono.zip
        mode: '0440'

    - name: Ensure /tmp/JetBrainsMono/ directory exists
      ansible.builtin.file:
        path: /tmp/JetBrainsMono
        state: directory
        recurse: yes


    # Unzip JetBrainsMono Font
    - name: Unzip JetBrainsMono Font
      ansible.builtin.unarchive:
        src: /tmp/JetBrainsMono.zip
        dest: /tmp/JetBrainsMono/
        remote_src: yes

    # Move JetBrainsMono Fonts to Fonts Directory
    - name: Move JetBrainsMono Fonts to Fonts Directory
      ansible.builtin.copy:
        src: /tmp/JetBrainsMono/
        dest: /home/{{ username }}/.local/share/fonts
        remote_src: yes

# Download Icomoon Feather Font from Feather Icons website
    - name: Download Icomoon Feather Font
      ansible.builtin.get_url:
        url: 'https://feathericons.com/feather.zip'  # Update with the correct download URL from Feather Icons
        dest: /tmp/feather.zip
        mode: '0440'

    - name: Ensure /tmp/ttf-icomoon-feather directory exists
      ansible.builtin.file:
        path: /tmp/feather
        state: directory
        recurse: yes

    - name: Unzip Icomoon Feather Font
      ansible.builtin.unarchive:
        src: /tmp/feather.zip
        dest: /tmp/feather
        remote_src: yes

    - name: Move Icomoon Feather Fonts to Fonts Directory
      ansible.builtin.copy:
        src: /tmp/feather/
        dest: /home/{{ username }}/.local/share/fonts
        remote_src: yes

    - name: Copy .tmux directory and its contents
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.tmux/
        dest: /home/{{ username }}/.tmux/
        directory_mode: yes

    - name: Copy .tmux.conf
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.tmux.conf
        dest: /home/{{ username }}/.tmux.conf

    - name: Copy .xinitrc
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.xinitrc
        dest: /home/{{ username }}/.xinitrc

    - name: Copy .Xresources
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.Xresources
        dest: /home/{{ username }}/.Xresources

    - name: Copy .zshrc
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.zshrc
        dest: /home/{{ username }}/.zshrc

    - name: Change ownership of user's home directory
      ansible.builtin.file:
        path: /home/{{ username }}
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
      become: yes

    - name: Set executable permissions for dotfiles
      ansible.builtin.find:
        paths: /home/{{ username }}/dotfiles
        recurse: yes
        patterns: '*.sh'  # Adjust this pattern to match the file extensions of your executable dotfiles
      register: executable_files

    - name: Make dotfiles executable
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: '0755'  # Set the desired executable permissions (e.g., 0755 for read and execute permissions)
      with_items: "{{ executable_files.files }}"      

    - name: Ensure tpm is cloned
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: /home/{{ username }}/.tmux/plugins/tpm
        version: master

    - name: Install tmux plugins using tpm
      ansible.builtin.shell: |
        tmux start-server
        tmux new-session -d
        sleep 1
        tmux source /home/{{ username }}/.tmux.conf
        sleep 1
        tmux kill-server
      args:
        executable: /bin/bash

