- name: Bootstrap development environment
  hosts: localhost
  become: yes
  become_user: root

  vars:
    target_user: "{{ username }}"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages with apt
      ansible.builtin.apt:
        name:
          - git
          - tmux
          - zsh
          - alacritty
          - i3
          - kitty
          - neofetch
          - picom
          - polybar
          - rofi
          - tree
          - unzip
          - xorg
          - xclip
        state: present

    # Clone dotfiles repository
    - name: Clone dotfiles repository
      ansible.builtin.git:
        repo: 'https://github.com/probird5/dotfiles'
        dest: "/home/{{ username }}/dotfiles"

    # Config file move
    - name: Ensure the .config directory exists
      ansible.builtin.file:
        path: "/home/{{ username }}/.config"
        state: directory

    - name: Copy the entire config directory
      ansible.builtin.copy:
        src: "/home/{{ username }}/dotfiles/.config"
        dest: "/home/{{ username }}/"

    # Backgrounds
    - name: Ensure backgrounds directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/Pictures/backgrounds
        state: directory

    - name: Copy backgrounds
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/background/
        dest: /home/{{ username }}/Pictures/backgrounds/
        directory_mode: yes

    # Ensure the font directory exists
    - name: Ensure font directory exists
      ansible.builtin.file:
        path: /home/{{ username }}/.local/share/fonts
        state: directory

    # Download Iosevka Font Zip
    - name: Download Iosevka Font Zip
      ansible.builtin.get_url:
        url: 'https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Iosevka.zip'
        dest: /tmp/Iosevka.zip
        mode: '0440'

    - name: Ensure /tmp/Iosevka directory exists
      ansible.builtin.file:
        path: /tmp/Iosevka
        state: directory
        recurse: yes

    # Unzip Iosevka Font
    - name: Unzip Iosevka Font
      ansible.builtin.unarchive:
        src: /tmp/Iosevka.zip
        dest: /tmp/Iosevka/
        remote_src: yes

    # Move Iosevka Fonts to Fonts Directory
    - name: Move Iosevka Fonts to Fonts Directory
      ansible.builtin.copy:
        src: /tmp/Iosevka/
        dest: /home/{{ username }}/.local/share/fonts
        remote_src: yes

    # Download JetBrainsMono Font Zip
    - name: Download JetBrainsMono Font Zip
      ansible.builtin.get_url:
        url: 'https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip'
        dest: /tmp/JetBrainsMono.zip
        mode: '0440'

    - name: Ensure /tmp/JetBrainsMono/ directory exists
      ansible.builtin.file:
        path: /tmp/JetBrainsMono
        state: directory
        recurse: yes


    # Unzip JetBrainsMono Font
    - name: Unzip JetBrainsMono Font
      ansible.builtin.unarchive:
        src: /tmp/JetBrainsMono.zip
        dest: /tmp/JetBrainsMono/
        remote_src: yes

    # Move JetBrainsMono Fonts to Fonts Directory
    - name: Move JetBrainsMono Fonts to Fonts Directory
      ansible.builtin.copy:
        src: /tmp/JetBrainsMono/
        dest: /home/{{ username }}/.local/share/fonts
        remote_src: yes

# Download Icomoon Feather Font from Feather Icons website
#    - name: Download Icomoon Feather Font
#     ansible.builtin.get_url:
#        url: 'https://feathericons.com/feather.zip'  # Update with the correct download URL from Feather Icons
#        dest: /tmp/feather.zip
#        mode: '0440'

          #    - name: Ensure /tmp/ttf-icomoon-feather directory exists
          # ansible.builtin.file:
          # path: /tmp/feather
          #state: directory
          #recurse: yes

          #    - name: Unzip Icomoon Feather Font
          #ansible.builtin.unarchive:
          #src: /tmp/feather.zip
          #dest: /tmp/feather
          #remote_src: yes

          #- name: Move Icomoon Feather Fonts to Fonts Directory
          #ansible.builtin.copy:
          #src: /tmp/feather/
          #dest: /home/{{ username }}/.local/share/fonts
          #remote_src: yes

    - name: Copy .tmux directory and its contents
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.tmux/
        dest: /home/{{ username }}/.tmux/
        directory_mode: yes

    - name: Copy .tmux.conf
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.tmux.conf
        dest: /home/{{ username }}/.tmux.conf

    - name: Copy .xinitrc
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.xinitrc
        dest: /home/{{ username }}/.xinitrc

    - name: Copy .Xresources
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.Xresources
        dest: /home/{{ username }}/.Xresources

    - name: Copy .zshrc
      ansible.builtin.copy:
        src: /home/{{ username }}/dotfiles/.zshrc
        dest: /home/{{ username }}/.zshrc

    - name: Find all files and directories in user's home directory, excluding .ansible
      ansible.builtin.find:
        paths: "/home/{{ username }}"
        recurse: yes
        excludes: ".ansible/*"
      register: files_and_directories


    - name: Change ownership of all files and directories in user's home directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      with_items: "{{ files_and_directories.files }}"
      become: yes

    - name: Ensure tpm is cloned
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: /home/{{ username }}/.tmux/plugins/tpm
        version: master

    - name: Install tmux plugins using tpm
      ansible.builtin.shell: |
        tmux start-server
        tmux new-session -d
        sleep 1
        tmux source /home/{{ username }}/.tmux.conf
        sleep 1
        tmux kill-server
      args:
        executable: /bin/bash

