- hosts: servers
  become: yes

  tasks:
    - name: apt update
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: installing packages
      apt:
        name:
          - tmux
          - net-tools
          - curl
          - vim
          - gcc
          - zsh
          - git
        state: present
        update_cache: true
      become: true

# want to add all my dotfiles
# Also want to git clone tmux plugin manager


# need to run "ansible-galaxy install gantsign.oh-my-zsh" first.
  roles: 
    - role: gantsign.oh-my-zsh
      users:
        - username: # Enter your username here
        
    
